### PR TITLE
chore: create version route

### PR DESCRIPTION
**Pull request by fernandodr19**
Create new route to return version data.

```
curl -i -X GET localhost:3001/version
```
```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 21 Apr 2021 14:19:30 GMT
Content-Length: 87

{"git_hash":"713421bee5293957ae68b22c62de5da6b38a42b2","time":"2021-04-21__11:19:20AM"}
```

### CODE REVIEW

**Comment by duarte2025** [comment]
@fernandodr19 Will the grpc gateway not be used anymore?

**Comment by fernandodr19** [comment]
> @fernandodr19 Will the grpc gateway not be used anymore?

@duarte2025 good question. Since this is more of a debug/internal route it made more sense to me to pack it with prometheus's ``/metrics``

**Comment by duarte2025** [comment]
@fernandodr19 Can you use prometheus ``/metrics`` with the gRPC gateway or only mux?

**Comment by fernandodr19** [comment]
> @fernandodr19 Can you use prometheus `/metrics` with the gRPC gateway or only mux?

@duarte2025 never did it. What would be the benefits?

**Review by alexgarzao — APPROVED** [review]
@duarte2025 , is not necessary to serve metrics/prom through gRPC.

Very nice PR @fernandodr19 :-)

**Review by victoraugustolls — APPROVED** [review]

**Review by duarte2025 — APPROVED** [review]

**Review by juceliofloresta — APPROVED** [review]

**Pull request merged**
