### PR TITLE
Feat/31

### PR DESCRIPTION
**Pull request by alexandreliberato**
gochk added to the go.mod file

### CODE REVIEW

**Comment by alexgarzao** [comment]
Hello @alexandreliberato .

I tried to test this PR, and there are errors. To fix, I did the following (git diff):

```
diff --git a/Makefile b/Makefile
index fcadc61..2a0ec6f 100644
--- a/Makefile
+++ b/Makefile
@@ -26,7 +26,7 @@ setup:
     github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
     golang.org/x/tools/cmd/goimports \
     github.com/kyoh86/richgo \
-    github.com/resotto/gochk
+    github.com/resotto/gochk/cmd/gochk
 
 
 .PHONY: test
diff --git a/go.mod b/go.mod
index c77f182..17a218d 100644
--- a/go.mod
+++ b/go.mod
@@ -15,6 +15,7 @@ require (
        github.com/kevinburke/go-bindata v3.22.0+incompatible
        github.com/kyoh86/richgo v0.3.3
        github.com/prometheus/client_golang v1.7.1
+       github.com/resotto/gochk v1.2.0
        github.com/sirupsen/logrus v1.7.0
        github.com/stretchr/testify v1.6.1
        golang.org/x/net v0.0.0-20200904194848-62affa334b73
@@ -23,5 +24,4 @@ require (
        google.golang.org/grpc v1.33.1
        google.golang.org/grpc/cmd/protoc-gen-go-grpc v1.0.1
        google.golang.org/protobuf v1.25.1-0.20201020201750-d3470999428b
-       gotest.tools v2.2.0+incompatible
 )
diff --git a/tools/tools.go b/tools/tools.go
index ea6e282..9b7b13f 100755
--- a/tools/tools.go
+++ b/tools/tools.go
@@ -12,6 +12,7 @@ import (
        _ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2"    // Generates swagger from gRPC definitions
        _ "github.com/kevinburke/go-bindata"                                  // converts any file into manageable Go source code
        _ "github.com/kyoh86/richgo"                                          // enrich go test outputs with text decorations
-       _ "golang.org/x/tools/cmd/goimports"                                  //Updates imports and formats code
+       _ "github.com/resotto/gochk/cmd/gochk"                                // Arch linter
+       _ "golang.org/x/tools/cmd/goimports"                                  // Updates imports and formats code
        _ "google.golang.org/grpc/cmd/protoc-gen-go-grpc"                     // gRPC generator
 )
```

Could you fix your PR?

**Comment by alexandreliberato** [comment]
@alexgarzao It is done!

**Review by alexgarzao — APPROVED** [review]

**Review by alexgarzao — CHANGES_REQUESTED** [review]
Hello. 

The file 'build/server' could not be committed. Please, add it to .gitignore, and remove from this PR.

**Review by alexgarzao — APPROVED** [review]
Nice! Thx Alexandre :-)

**Pull request merged**
