### PR TITLE
docs: roadmap proposal

### PR DESCRIPTION
**Pull request by alexgarzao**
Hello people!

The main intention here is to define the project's roadmap.

Feel free to give your opinion about it :-)

### CODE REVIEW

**Review by duarte2025 — APPROVED** [review]

**Comment by alexandreliberato** [comment]
as q new project maybe it would be nice to have a linter for the system architecture like https://github.com/fe3dback/go-arch-lint

**Comment by alexrios** [comment]
> Hello! As a new project maybe it would be nice to have a linter for the system architecture like https://github.com/fe3dback/go-arch-lint

Good catch! Another option with less options but simpler: https://github.com/resotto/gochk

**Comment by alexandreliberato** [comment]
> > Hello! As a new project maybe it would be nice to have a linter for the system architecture like https://github.com/fe3dback/go-arch-lint
> 
> Good catch! Another option with less options but simpler: https://github.com/resotto/gochk

I think that's a good idea to start simpler.

**Comment by alexgarzao** [comment]
> > > Hello! As a new project maybe it would be nice to have a linter for the system architecture like https://github.com/fe3dback/go-arch-lint
> > 
> > 
> > Good catch! Another option with less options but simpler: https://github.com/resotto/gochk
> 
> I think that's a good idea to start simpler. But to start to check it before it becomes messy (or depending too much on human validation).

I agree. And gochk seems to be simple and useful.

**Comment by guilhermebr** [comment]
Moving this discussion to the appropriate place: https://github.com/stone-co/the-amazing-ledger/issues/30

**Pull request closed without merging**
