### PR TITLE
refact: split generic error to be friendlier

### PR DESCRIPTION
**Pull request by thalissonfelipe**
This PR does:
- Refact ErrInvalidAccountStructure error message to provide better feedback.
- Add three more errors related to AccountQuery and AccountPath.
    - ErrInvalidAccountComponentSize: when the component size is empty or has more than 255 characters.
    - ErrInvalidAccountComponentCharacters: when the component has unsupported characters.
    - ErrAccountPathViolation: when the account violates depth restrictions.

### CODE REVIEW

**Review by matheusmosca — APPROVED** [review]
The `NewAccountQuery` constructor shouldn't validate if an accountPath starts with a kown depth config like `assets` and `liability`? If I send a path that begins with `asset` instead of `assets`, I'll get an error for this? The `AccountQuery` does not need this validation?

It's not related to this PR actually, but I just noticed this possible issue when I was reviewing it. If my comment was not clear, I'm talking about [this](https://github.com/stone-co/the-amazing-ledger/blob/20027a234fe31c7a517fc922fa7db30af31b9bfd/app/domain/vos/account_path.go#L104) validation. Isn't it missing in `NewAccountQuery`?

**Comment by thalissonfelipe** [comment]
> The `NewAccountQuery` constructor shouldn't validate if an accountPath starts with a kown depth config like `assets` and `liability`? If I send a path that begins with `asset` instead of `assets`, I'll get an error for this? The `AccountQuery` does not need this validation?
> 
> It's not related to this PR actually, but I just noticed this possible issue when I was reviewing it. If my comment was not clear, I'm talking about [this](https://github.com/stone-co/the-amazing-ledger/blob/20027a234fe31c7a517fc922fa7db30af31b9bfd/app/domain/vos/account_path.go#L104) validation. Isn't it missing in `NewAccountQuery`?

**Comment by thalissonfelipe** [comment]
Yes, AccountQuery doesn't need this validation because it's more flexible. The only validation is to check whether the number of components in the account query is greater than the maximum depth size. It doesn't make sense if your account query has four components, but the maximum depth size is 3.

**Comment by thalissonfelipe** [comment]
Hello @matheusmosca. We discussed internally and added the depth restriction again in the AccountQuery constructor. But, we only do this when the query component doesn't have special characters. Why? If the query has special characters, we let it pass because the query is flexible as I said before, but if it doesn't, we check if there is a depth restriction and do the validation if necessary.

You can check the changes [here]( https://github.com/stone-co/the-amazing-ledger/pull/90/files#diff-d8d568e0fce5c997e901a295cdca1afd7f93d064281d78caabd4ebcee80ed157R21).

**Review by alexandreliberato — APPROVED** [review]

**Review by matheusmosca — APPROVED** [review]

**Review by victoraugustolls — APPROVED** [review]

**Pull request merged**
